# Generated by Django 4.0.2 on 2022-06-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseRental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dest',
            name='location',
            field=models.CharField(default='hyderabad', max_length=100),
        ),
    ]
