# Generated by Django 4.0.2 on 2022-06-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseRental', '0003_dest_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dest',
            name='college',
        ),
        migrations.RemoveField(
            model_name='dest',
            name='location',
        ),
        migrations.RemoveField(
            model_name='dest',
            name='price',
        ),
    ]
