# Generated by Django 4.0.2 on 2022-06-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseRental', '0004_remove_dest_college_remove_dest_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dest',
            name='age',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='dest',
            name='collegeinfo',
            field=models.TextField(default='vignan'),
        ),
    ]
