# Generated by Django 4.0.2 on 2022-06-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseRental', '0005_dest_age_dest_collegeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('cost', models.IntegerField(default=15)),
                ('facility', models.TextField(default='3BHK')),
            ],
        ),
    ]
