# Generated by Django 4.0.2 on 2022-06-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseRental', '0006_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='phone',
            field=models.IntegerField(default=15),
        ),
    ]
