# Generated by Django 4.0.2 on 2022-07-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseRental', '0007_house_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='dest',
            name='img',
            field=models.ImageField(default='NULL', upload_to='pics'),
        ),
    ]
