# Generated by Django 4.0.2 on 2022-07-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseRental', '0008_dest_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('location', models.TextField()),
                ('user_dp', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
