# Generated by Django 4.0.2 on 2022-07-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseRental', '0010_house_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminhouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=20)),
                ('facility', models.TextField(max_length=20)),
                ('phone', models.TextField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='house',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
