# Generated by Django 4.0.2 on 2022-07-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseRental', '0011_adminhouses_alter_house_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='dest',
            name='url',
            field=models.URLField(default='NULL', max_length=2000),
        ),
    ]
