# Generated by Django 4.0.2 on 2022-07-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseRental', '0012_dest_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dest',
            name='img',
            field=models.ImageField(default='NULL', upload_to='pics/%y'),
        ),
        migrations.AlterField(
            model_name='house',
            name='img',
            field=models.ImageField(upload_to='pics quaality'),
        ),
    ]
