# Generated by Django 4.0.2 on 2022-07-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseRental', '0013_alter_dest_img_alter_house_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dest',
            name='img',
            field=models.ImageField(default='NULL', upload_to='new pics'),
        ),
    ]
