# Generated by Django 4.0.2 on 2022-07-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseRental', '0015_rename_collegeinfo_dest_address_rename_age_dest_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminhouses',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='adminhouses',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='adminhouses',
            name='type',
        ),
        migrations.AddField(
            model_name='adminhouses',
            name='IMAGE',
            field=models.ImageField(default='NULL', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='adminhouses',
            name='PRICE',
            field=models.IntegerField(default=250),
        ),
    ]
