# Generated by Django 4.0.2 on 2022-07-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseRental', '0017_delete_user_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='dest',
            name='UPLOAD_HOUSE_IMAGE2',
            field=models.ImageField(default='NULL', upload_to='new pics'),
        ),
        migrations.AddField(
            model_name='dest',
            name='UPLOAD_HOUSE_IMAGE3',
            field=models.ImageField(default='NULL', upload_to='new pics'),
        ),
    ]
