# Generated by Django 4.0.2 on 2022-07-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseRental', '0018_dest_upload_house_image2_dest_upload_house_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminhouses',
            name='PLACE',
            field=models.TextField(default='HYDERABAD'),
        ),
    ]
