# Generated by Django 4.0.2 on 2022-07-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseRental', '0019_adminhouses_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminhouses2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMAGE', models.ImageField(default='NULL', upload_to='pics')),
                ('PRICE', models.IntegerField(default=250)),
                ('PLACE', models.TextField(default='HYDERABAD')),
            ],
        ),
        migrations.CreateModel(
            name='adminhouses3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMAGE', models.ImageField(default='NULL', upload_to='pics')),
                ('PRICE', models.IntegerField(default=250)),
                ('PLACE', models.TextField(default='HYDERABAD')),
            ],
        ),
    ]
