# Generated by Django 4.0.2 on 2022-07-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseRental', '0020_adminhouses2_adminhouses3'),
    ]

    operations = [
        migrations.AddField(
            model_name='dest',
            name='ADDRESS_URL',
            field=models.URLField(default='NULL'),
        ),
    ]
