# Generated by Django 4.0.2 on 2022-07-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseRental', '0021_dest_address_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dest',
            name='AREA',
            field=models.CharField(default='urban', max_length=50),
        ),
    ]
