# Generated by Django 4.0.2 on 2022-07-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseRental', '0022_dest_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='dest',
            name='STATE',
            field=models.CharField(default='krishna', max_length=50),
        ),
    ]
