# Generated by Django 4.0.2 on 2022-08-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseRental', '0023_dest_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='phone',
            field=models.IntegerField(default=15, max_length=12),
        ),
    ]
